//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadorGedWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validacoes
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string NomeEmpresa { get; set; }
        public long Quantidade { get; set; }
    }
}
